# Generated by Django 3.2.13 on 2023-05-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.TextField()),
                ('backdrop_path', models.TextField()),
                ('genre_ids', models.TextField()),
                ('movie_id', models.IntegerField()),
                ('original_language', models.TextField()),
                ('original_title', models.TextField()),
                ('overview', models.TextField()),
                ('popularity', models.IntegerField()),
                ('poster_path', models.TextField()),
                ('release_date', models.TextField()),
                ('title', models.TextField()),
                ('video', models.TextField()),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
            ],
        ),
    ]
